version: "3"
services:
  server:
    image: node:10.15-alpine
    environment:
      - PORT=4000
    volumes:
      - .:/opt/code
    ports:
      - "4000:4000"
    depends_on:
      - db
    working_dir: /opt/code
    command: sh -c "npm install && npm run build && bin/wait-for db:5432 -t 30 -- npm run migrate && npm run watch"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
