version: "3"
services:
  server:
    image: node:10.15-alpine
    volumes:
      - .:/opt/code
    ports:
      - "3000:3000"
    working_dir: /opt/code
    command: sh -c "npm install && npm run watch"
